<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class InstitucionesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    /*
    public function run(): void
    {
        Instituto::create(['nombre' => 'CENTRO CULTURAL EUROPEO DE ESTUDIOS UNIVERSITARIOS DE HIDALGO']);
        Instituto::create(['nombre' => 'CENTRO DE ESTUDIO VALORES CON LIBERTAD, "CEVAL"']);
        Instituto::create(['nombre' => 'CENTRO DE ESTUDIOS SUPERIORES ANTARES']);
        Instituto::create(['nombre' => 'CENTRO DE ESTUDIOS SUPERIORES EN GASTRONOMÍA Y TURISMO']);
        Instituto::create(['nombre' => 'CENTRO DE ESTUDIOS SUPERIORES IDDEA']);
        Instituto::create(['nombre' => 'CENTRO DE ESTUDIOS UNIVERSITARIOS DE HIDALGO']);
        Instituto::create(['nombre' => 'CENTRO DE ESTUDIOS UNIVERSITARIOS LEONARDO DE VINCI']);
        Instituto::create(['nombre' => 'CENTRO DE ESTUDIOS UNIVERSITARIOS MOYOCOYANI']);
        Instituto::create(['nombre' => 'CENTRO DE ESTUDIOS UNIVERSITARIOS VIZCAYA DE LAS AMÉRICAS']);
        Instituto::create(['nombre' => 'CENTRO DE TERAPIA FAMILIAR Y DE PAREJA']);
        Instituto::create(['nombre' => 'CENTRO HIDALGUENSE DE ESTUDIOS SUPERIORES']);
        Instituto::create(['nombre' => 'CENTRO HUMANISTA DE INVESTIGACIÓN Y DESARROLLO MULTIDISCIPLINARIO']);
        Instituto::create(['nombre' => 'CENTRO REGIONAL DE EDUCACIÓN NORMAL BENITO JUÁREZ']);
        Instituto::create(['nombre' => 'CENTRO UNIVERSITARIO ALLENDE']);
        Instituto::create(['nombre' => 'CENTRO UNIVERSITARIO CONTINENTAL']);
        Instituto::create(['nombre' => 'CENTRO UNIVERSITARIO DE DESARROLLO INTELECTUAL']);
        Instituto::create(['nombre' => 'CENTRO UNIVERSITARIO DE EDUCACIÓN A DISTANCIA']);
        Instituto::create(['nombre' => 'CENTRO UNIVERSITARIO DE ESTUDIOS HANS GROSS']);
        Instituto::create(['nombre' => 'CENTRO UNIVERSITARIO DE ESTUDIOS SUPERIORES DE MÉXICO']);
        Instituto::create(['nombre' => 'CENTRO UNIVERSITARIO DE LA CIUDAD DE MÉXICO']);
        Instituto::create(['nombre' => 'CENTRO UNIVERSITARIO DEL ORIENTE DE HIDALGO']);
        Instituto::create(['nombre' => 'CENTRO UNIVERSITARIO HIDALGUENSE']);
        Instituto::create(['nombre' => 'CENTRO UNIVERSITARIO HIDALGUENSE A.C.']);
        Instituto::create(['nombre' => 'CENTRO UNIVERSITARIO INTERAMERICANO']);
        Instituto::create(['nombre' => 'CENTRO UNIVERSITARIO METROPOLITANO HIDALGO']);
        Instituto::create(['nombre' => 'CENTRO UNIVERSITARIO SIGLO XXI']);
        Instituto::create(['nombre' => 'CENTRO UNIVERSITARIO SIGLO XXI, SEDE ZACUALTIPAN']);
        Instituto::create(['nombre' => 'CENTRO UNIVERSITARIO VASCO DE QUIROGA DE HUEJUTLA']);
        Instituto::create(['nombre' => 'CÍRCULO DE ESTUDIOS DE LOGOTERAPIA Y ANÁLISIS EXISTENCIAL']);
        Instituto::create(['nombre' => 'COLEGIO ANAHUAC']);
        Instituto::create(['nombre' => 'COLEGIO DE ESTUDIOS SUPERIORES HISPANOAMERICANO']);
        Instituto::create(['nombre' => 'COLEGIO DE ORTODONCIA, ORTOPEDIA E IMPLANTOLOGÍA S.C.']);
        Instituto::create(['nombre' => 'COLEGIO DE TRAFICO ADUANAL SOBRECARGO Y ESPECIALIDADES']);
        Instituto::create(['nombre' => 'COLEGIO LIBRE DE HIDALGO']);
        Instituto::create(['nombre' => 'COLEGIO PABLO LATAPI SARRE']);
        Instituto::create(['nombre' => 'COLEGIO REAL HIDALGO']);
        Instituto::create(['nombre' => 'COLEGIO SUPERIOR DE ODONTOLOGÍA']);
        Instituto::create(['nombre' => 'COMPLEJO UNIVERSITARIO GRIDEHS']);
        Instituto::create(['nombre' => 'DIRECCIÓN DE POSGRADO E INVESTIGACIÓN']);
        Instituto::create(['nombre' => 'DIVISIÓN EN CIENCIAS ADMINISTRATIVAS']);
        Instituto::create(['nombre' => 'EL COLEGIO DEL ESTADO DE HIDALGO']);
        Instituto::create(['nombre' => 'ESCUELA BANCARIA Y COMERCIAL, CAMPUS PACHUCA']);
        Instituto::create(['nombre' => 'ESCUELA DE ARQUITECTURA']);
        Instituto::create(['nombre' => 'ESCUELA DE ARQUITECTURA Y DISEÑO']);
        Instituto::create(['nombre' => 'ESCUELA DE DERECHO']);
        Instituto::create(['nombre' => 'ESCUELA DE ESTUDIOS SUPERIORES DE HIDALGO "EESUPH"']);
        Instituto::create(['nombre' => 'ESCUELA DE GASTRONOMÍA']);
        Instituto::create(['nombre' => 'ESCUELA DE MEDICINA INTERMÉDICA']);
        Instituto::create(['nombre' => 'ESCUELA DE MÚSICA DEL ESTADO DE HIDALGO']);
        Instituto::create(['nombre' => 'ESCUELA DE PEDAGOGÍA']);
        Instituto::create(['nombre' => 'ESCUELA JURÍDICA Y FORENSE DEL SURESTE, PLANTEL PACHUCA']);
        Instituto::create(['nombre' => 'ESCUELA LIBRE DE DERECHO DEL ESTADO DE HIDALGO']);
        Instituto::create(['nombre' => 'ESCUELA NORMAL SUPERIOR DE TULANCINGO, LUIS DONALDO COLOSIO MURRIETA']);
        Instituto::create(['nombre' => 'ESCUELA NORMAL SUPERIOR DEL ESTADO DE HIDALGO, S.C.']);
        Instituto::create(['nombre' => 'ESCUELA NORMAL SUPERIOR MIGUEL HIDALGO']);
        Instituto::create(['nombre' => 'ESCUELA NORMAL SUPERIOR PUBLICA DEL ESTADO DE HIDALGO']);
        Instituto::create(['nombre' => 'ESCUELA SUPERIOR ATOTONILCO DE TULA']);
        Instituto::create(['nombre' => 'ESCUELA SUPERIOR DE ACTOPAN']);
        Instituto::create(['nombre' => 'ESCUELA SUPERIOR DE APAN']);
        Instituto::create(['nombre' => 'ESCUELA SUPERIOR DE CIUDAD SAHAGÚN']);
        Instituto::create(['nombre' => 'ESCUELA SUPERIOR DE EDUCACIÓN ARTÍSTICA ARMONIARTE']);
        Instituto::create(['nombre' => 'ESCUELA SUPERIOR DE HUEJUTLA']);
        Instituto::create(['nombre' => 'ESCUELA SUPERIOR DE INGENIERÍA MECÁNICA, PLANTEL PACHUCA']);
        Instituto::create(['nombre' => 'ESCUELA SUPERIOR DE TEPEJI DEL RÍO']);
        Instituto::create(['nombre' => 'ESCUELA SUPERIOR DE TIZAYUCA']);
        Instituto::create(['nombre' => 'ESCUELA SUPERIOR DE TLAHUELILPAN']);
        Instituto::create(['nombre' => 'ESCUELA SUPERIOR DE ZIMAPÁN']);
        Instituto::create(['nombre' => 'FACULTAD DE CIENCIAS ADMINISTRATIVAS']);
        Instituto::create(['nombre' => 'FACULTAD DE CIENCIAS HUMANAS']);
        Instituto::create(['nombre' => 'FACULTAD DE DERECHO']);
        Instituto::create(['nombre' => 'INSTITUTO DE ADMINISTRACIÓN PÚBLICA DEL ESTADO DE HIDALGO A.C.']);
        Instituto::create(['nombre' => 'INSTITUTO DE ARTES']);
        Instituto::create(['nombre' => 'INSTITUTO DE CIENCIAS AGROPECUARIAS']);
        Instituto::create(['nombre' => 'INSTITUTO DE CIENCIAS BÁSICAS E INGENIERÍA (ICBI)']);
        Instituto::create(['nombre' => 'INSTITUTO DE CIENCIAS DE LA SALUD (ICSA)']);
        Instituto::create(['nombre' => 'INSTITUTO DE CIENCIAS ECONÓMICO ADMINISTRATIVAS (ICEA)']);
        Instituto::create(['nombre' => 'INSTITUTO DE CIENCIAS SOCIALES Y HUMANIDADES (ICSHU)']);
        Instituto::create(['nombre' => 'INSTITUTO DE CIENCIAS Y ESTUDIOS SUPERIORES DE HIDALGO']);
        Instituto::create(['nombre' => 'INSTITUTO DE CIENCIAS Y ESTUDIOS SUPERIORES DE HIDALGO, CAMPUS PACHUCA']);
        Instituto::create(['nombre' => 'INSTITUTO DE DESARROLLO PROFESIONAL DE HIDALGO (IDEPH)']);
        Instituto::create(['nombre' => 'INSTITUTO DE ENSEÑANZA SUPERIOR ALFONSO CRAVIOTO']);
        Instituto::create(['nombre' => 'INSTITUTO DE ESTUDIOS SUPERIORES DE PROGRESO DE OBREGON, HIDALGO']);
        Instituto::create(['nombre' => 'INSTITUTO DE ESTUDIOS SUPERIORES DEL ALTIPLANO (IESA)']);
        Instituto::create(['nombre' => 'INSTITUTO DE ESTUDIOS SUPERIORES ELISE FREINET']);
        Instituto::create(['nombre' => 'INSTITUTO DE ESTUDIOS SUPERIORES ISIMA PLANTEL PACHUCA']);
        Instituto::create(['nombre' => 'INSTITUTO DE ESTUDIOS SUPERIORES JOHN F. KENNEDY']);
        Instituto::create(['nombre' => 'INSTITUTO DE ESTUDIOS SUPERIORES TIOZIHUATL']);
        Instituto::create(['nombre' => 'INSTITUTO DE FORMACION PROFESIONAL']);
        Instituto::create(['nombre' => 'INSTITUTO DE POSGRADO EN PSICOTERAPIA COGNITIVO-CONDUCTUAL']);
        Instituto::create(['nombre' => 'INSTITUTO GASTRONÓMICO HIDALGUENSE']);
        Instituto::create(['nombre' => 'INSTITUTO MEXICANO DE TERAPIAS BREVES']);
        Instituto::create(['nombre' => 'INSTITUTO TECNOLOGICO CULTURAL DE HIDALGO']);
        Instituto::create(['nombre' => 'INSTITUTO TECNOLÓGICO DE ATITALAQUIA']);
        Instituto::create(['nombre' => 'INSTITUTO TECNOLOGICO DE EDUCACION SUPERIOR']);
        Instituto::create(['nombre' => 'INSTITUTO TECNOLÓGICO DE ESTUDIOS SUPERIORES DE MONTERREY CAMPUS HIDALGO']);
        Instituto::create(['nombre' => 'INSTITUTO TECNOLÓGICO DE HUEJUTLA']);
        Instituto::create(['nombre' => 'INSTITUTO TECNOLÓGICO DE LA CONSTRUCCIÓN']);
        Instituto::create(['nombre' => 'INSTITUTO TECNOLOGICO DE PACHUCA']);
        Instituto::create(['nombre' => 'INSTITUTO TECNOLÓGICO LATINOAMERICANO']);
        Instituto::create(['nombre' => 'INSTITUTO TECNOLÓGICO LATINOAMERICANO CAMPUS TULA']);
        Instituto::create(['nombre' => 'INSTITUTO TECNOLÓGICO SUPERIOR DE HUICHAPAN']);
        Instituto::create(['nombre' => 'INSTITUTO TECNOLÓGICO SUPERIOR DEL OCCIDENTE DEL ESTADO DE HIDALGO']);
        Instituto::create(['nombre' => 'INSTITUTO TECNOLÓGICO SUPERIOR DEL ORIENTE DEL ESTADO DE HIDALGO (ITESA)']);
        Instituto::create(['nombre' => 'INSTITUTO UNIVERSITARIO DE LAS NACIONES HISPANAS']);
        Instituto::create(['nombre' => 'INSTITUTO UNIVERSITARIO DEL CENTRO DE MÉXICO CAMPUS ACTOPAN']);
        Instituto::create(['nombre' => 'INSTITUTO UNIVERSITARIO DEL CENTRO DE MÉXICO CAMPUS PACHUCA']);
        Instituto::create(['nombre' => 'INSTITUTO UNIVERSITARIO DEL CENTRO DE MÉXICO CAMPUS TULA DE ALLENDE']);
        Instituto::create(['nombre' => 'NORMAL DE LAS HUASTECAS']);
        Instituto::create(['nombre' => 'NORMAL RURAL LUIS VILLARREAL']);
        Instituto::create(['nombre' => 'NORMAL SIERRA HIDALGUENSE']);
        Instituto::create(['nombre' => 'NORMAL VALLE DEL MEZQUITAL']);
        Instituto::create(['nombre' => 'SAN FELIPE DE JESÚS']);
        Instituto::create(['nombre' => 'SISTEMA DE UNIVERSIDAD VIRTUAL']);
        Instituto::create(['nombre' => 'UNIDAD ACADÉMICA DE CHAPULHUACÁN']);
        Instituto::create(['nombre' => 'UNIDAD ACADÉMICA DE CUAUTEPEC']);
        Instituto::create(['nombre' => 'UNIDAD ACADÉMICA DE METZTITLÁN']);
        Instituto::create(['nombre' => 'UNIDAD ACADEMICA DE SANTA ÚRSULA']);
        Instituto::create(['nombre' => 'UNIDAD ACADÉMICA DE TEPETITLÁN']);
        Instituto::create(['nombre' => 'UNIDAD ACADÉMICA DE TEZONTEPEC DE ALDAMA']);
        Instituto::create(['nombre' => 'UNIDAD PROFESIONAL INTERDISCIPLINARIA DE INGENIERÍA CAMPUS HIDALGO']);
        Instituto::create(['nombre' => 'UNIVERSIDAD CANADIENSE']);
        Instituto::create(['nombre' => 'UNIVERSIDAD CIENTÍFICA LATINO AMERICANA DE HIDALGO']);
        Instituto::create(['nombre' => 'UNIVERSIDAD DEL DESARROLLO PROFESIONAL (TULA DE ALLENDE)']);
        Instituto::create(['nombre' => 'UNIVERSIDAD DEL DESARROLLO PROFESIONAL (HUICHAPAN)']);
        Instituto::create(['nombre' => 'UNIVERSIDAD DEL FUTBOL Y CIENCIAS DEL DEPORTE']);
        Instituto::create(['nombre' => 'UNIVERSIDAD DEL NUEVO MÉXICO']);
        Instituto::create(['nombre' => 'UNIVERSIDAD DEL NUEVO MÉXICO, CAMPUS HUICHAPAN']);
        Instituto::create(['nombre' => 'UNIVERSIDAD DIGITAL DEL ESTADO DE HIDALGO']);
        Instituto::create(['nombre' => 'UNIVERSIDAD ETAC CAMPUS TULANCINGO']);
        Instituto::create(['nombre' => 'UNIVERSIDAD HUMANISTA HIDALGO']);
        Instituto::create(['nombre' => 'UNIVERSIDAD IBEROMEXICANA DE HIDALGO']);
        Instituto::create(['nombre' => 'UNIVERSIDAD INECUH']);
        Instituto::create(['nombre' => 'UNIVERSIDAD INTERACTIVA MILENIO']);
        Instituto::create(['nombre' => 'UNIVERSIDAD INTERAMERICANA PARA EL DESARROLLO']);
        Instituto::create(['nombre' => 'UNIVERSIDAD INTERAMERICANA PARA EL DESARROLLO, SEDE TULA']);
        Instituto::create(['nombre' => 'UNIVERSIDAD INTERCULTURAL DEL ESTADO DE HIDALGO']);
        Instituto::create(['nombre' => 'UNIVERSIDAD INTERGLOBAL']);
        Instituto::create(['nombre' => 'UNIVERSIDAD PEDAGÓGICA NACIONAL-HIDALGO UNIDAD 131 SEDE CENTRAL PACHUCA']);
        Instituto::create(['nombre' => 'UNIVERSIDAD PEDAGÓGICA NACIONAL-HIDALGO UNIDAD 131 SEDE REGIONAL HUEJUTLA']);
        Instituto::create(['nombre' => 'UNIVERSIDAD PEDAGÓGICA NACIONAL-HIDALGO UNIDAD 131 SEDE REGIONAL IXMIQUILPAN']);
        Instituto::create(['nombre' => 'UNIVERSIDAD PEDAGÓGICA NACIONAL-HIDALGO UNIDAD 131 SEDE REGIONAL JACALA']);
        Instituto::create(['nombre' => 'UNIVERSIDAD PEDAGÓGICA NACIONAL-HIDALGO UNIDAD 131 SEDE REGIONAL TENANGO DE DORIA']);
        Instituto::create(['nombre' => 'UNIVERSIDAD PEDAGÓGICA NACIONAL-HIDALGO UNIDAD 131 SEDE REGIONAL TULA DE ALLENDE']);
        Instituto::create(['nombre' => 'UNIVERSIDAD PEDAGÓGICA NACIONAL-HIDALGO UNIDAD 131 SEDE REGIONAL TULANCINGO']);
        Instituto::create(['nombre' => 'UNIVERSIDAD POLITÉCNICA DE FRANCISCO I. MADERO']);
        Instituto::create(['nombre' => 'UNIVERSIDAD POLITÉCNICA DE HUEJUTLA']);
        Instituto::create(['nombre' => 'UNIVERSIDAD POLITÉCNICA DE LA ENERGÍA']);
        Instituto::create(['nombre' => 'UNIVERSIDAD POLITÉCNICA DE PACHUCA']);
        Instituto::create(['nombre' => 'UNIVERSIDAD POLITÉCNICA DE TULANCINGO']);
        Instituto::create(['nombre' => 'UNIVERSIDAD POLITÉCNICA METROPOLITANA DE HIDALGO']);
        Instituto::create(['nombre' => 'UNIVERSIDAD PRIVADA DEL CENTRO']);
        Instituto::create(['nombre' => 'UNIVERSIDAD TECNOLÓGICA DE LA SIERRA HIDALGUENSE']);
        Instituto::create(['nombre' => 'UNIVERSIDAD TECNOLÓGICA DE LA ZONA METROPOLITANA DEL VALLE DE MÉXICO']);
        Instituto::create(['nombre' => 'UNIVERSIDAD TECNOLÓGICA DE MINERAL DE LA REFORMA']);
        Instituto::create(['nombre' => 'UNIVERSIDAD TECNOLÓGICA DE TULANCINGO']);
        Instituto::create(['nombre' => 'UNIVERSIDAD TECNOLÓGICA DEL VALLE DEL MEZQUITAL']);
        Instituto::create(['nombre' => 'UNIVERSIDAD TECNOLÓGICA INTERNACIONAL CAMPUS HIDALGO TLAXCOAPAN']);
        Instituto::create(['nombre' => 'UNIVERSIDAD TECNOLÓGICA MINERA DE ZIMAPÁN']);
        Instituto::create(['nombre' => 'UNIVERSIDAD TECNOLÓGICA TULA-TEPEJI']);

    }*/
}
